package com.assignment.catalog.service.impl;

import com.assignment.catalog.dto.LocationDTO;
import com.assignment.catalog.entity.Location;
import com.assignment.catalog.exception.BadRequestException;
import com.assignment.catalog.exception.ResourceNotFoundException;
import com.assignment.catalog.mapper.CatalogMapper;
import com.assignment.catalog.repository.LocationRepository;
import com.assignment.catalog.repository.TheatreRepository;
import com.assignment.catalog.service.LocationService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class LocationServiceImpl implements LocationService {

    private final LocationRepository locationRepository;
    private final TheatreRepository theatreRepository;
    private final CatalogMapper mapper;

    @Override
    public LocationDTO createLocation(LocationDTO locationDTO) {
        Location location = mapper.toLocation(locationDTO);
        location.setId(null); // Ensure id is generated by DB
        Location savedLocation = locationRepository.save(location);
        return mapper.toLocationDTO(savedLocation);
    }

    @Override
    public LocationDTO getLocationById(String id) {
        Location location = locationRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Location not found with id: " + id));
        return mapper.toLocationDTO(location);
    }

    @Override
    public List<LocationDTO> getAllLocations() {
        return locationRepository.findAll().stream()
                .map(mapper::toLocationDTO)
                .collect(Collectors.toList());
    }

    @Override
    public LocationDTO updateLocation(String id, LocationDTO locationDTO) {
        Location location = locationRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Location not found with id: " + id));
        location.setCity(locationDTO.getCity());
        location.setState(locationDTO.getState());
        location.setCountry(locationDTO.getCountry());
        Location updated = locationRepository.save(location);
        return mapper.toLocationDTO(updated);
    }

    @Override
    public void deleteLocation(String id) {
        if (!locationRepository.existsById(id)) {
            throw new ResourceNotFoundException("Location not found with id: " + id);
        }
        if (theatreRepository.existsByLocationId(id)) {
            throw new BadRequestException("Cannot delete location as it is currently linked to existing theatres");
        }
        locationRepository.deleteById(id);
    }
}
